#!/bin/sh

while :
do
process=`ps -ef | grep ultraSonic | grep -v "grep" | wc -l`
        if [ ${process} -eq 0 ];then 
                echo "process down"

                cd /home/pi/CodeFair_Always
                ./ultraSonic &                      
        fi

done
